package orchestrator

import (
	"bufio"
	"fmt"
	"io"
	"strings"
	"time"

	"github.com/Yashh56/atlas/internal/config"
)

// CheckApproval determines if a deployment is approved based on config.
// If config.Approval is "manual", it prompts the user on stdout/stdin.
// If config.Approval is "auto", it approves immediately.
// Returns true if approved, false if declined.
func CheckApproval(cfg *config.Config, dep *DeploymentState, in io.Reader, out io.Writer) bool {
	if cfg.Approval == "auto" {
		now := time.Now().UTC()
		user := "auto"
		dep.Approval.Required = false
		dep.Approval.ApprovedBy = &user
		dep.Approval.ApprovedAt = &now
		return true
	}

	// Manual approval
	fmt.Fprintf(out, "\n--- Deployment Approval ---\n")
	fmt.Fprintf(out, "Provider:    %s\n", dep.Provider)
	fmt.Fprintf(out, "Environment: %s\n", dep.Environment)
	fmt.Fprintf(out, "Proceed with deployment? [y/N]: ")

	scanner := bufio.NewScanner(in)
	if !scanner.Scan() {
		return false
	}
	
	ans := strings.ToLower(strings.TrimSpace(scanner.Text()))
	if ans == "y" || ans == "yes" {
		now := time.Now().UTC()
		user := "cli-user"
		dep.Approval.Required = true
		dep.Approval.ApprovedBy = &user
		dep.Approval.ApprovedAt = &now
		return true
	}

	return false
}

// CheckCommitApproval prompts the user whether they want to commit and push
// automatic fixes generated by the LLM.
func CheckCommitApproval(in io.Reader, out io.Writer) bool {
	fmt.Fprintf(out, "\n--- Auto-Fix Approval ---\n")
	fmt.Fprintf(out, "LLM automatically fixed build errors. Do you want to commit and push these fixes? [y/N]: ")

	scanner := bufio.NewScanner(in)
	if !scanner.Scan() {
		return false
	}
	
	ans := strings.ToLower(strings.TrimSpace(scanner.Text()))
	if ans == "y" || ans == "yes" {
		return true
	}

	return false
}

// RecordDeployment updates the DeploymentState with a new successful deployment URL,
// cycling the current URL to previous.
func RecordDeployment(dep *DeploymentState, newURL string) {
	if dep.DeploymentURL != nil {
		dep.PreviousDeploymentURL = dep.DeploymentURL
	}
	dep.DeploymentURL = &newURL
	// Rollback is not supported yet
	dep.RollbackAvailable = false
}
