package orchestrator

import (
	"bufio"
	"fmt"
	"io"
	"strings"
	"time"

	"github.com/Yashh56/atlas/internal/config"
)

// CheckApproval determines if a deployment is approved based on config.
// If config.Approval is "manual", it prompts the user on stdout/stdin.
// If config.Approval is "auto", it approves immediately.
// Returns true if approved, false if declined.
func CheckApproval(cfg *config.Config, dep *DeploymentState, in io.Reader, out io.Writer) bool {
	if cfg.Approval == "auto" {
		now := time.Now().UTC()
		user := "auto"
		dep.Approval.Required = false
		dep.Approval.ApprovedBy = &user
		dep.Approval.ApprovedAt = &now
		return true
	}

	// Manual approval
	fmt.Fprintf(out, "\n--- Deployment Approval ---\n")
	fmt.Fprintf(out, "Provider:    %s\n", dep.Provider)
	fmt.Fprintf(out, "Environment: %s\n", dep.Environment)
	fmt.Fprintf(out, "Proceed with deployment? [y/N]: ")

	scanner := bufio.NewScanner(in)
	if !scanner.Scan() {
		return false
	}
	
	ans := strings.ToLower(strings.TrimSpace(scanner.Text()))
	if ans == "y" || ans == "yes" {
		now := time.Now().UTC()
		user := "cli-user"
		dep.Approval.Required = true
		dep.Approval.ApprovedBy = &user
		dep.Approval.ApprovedAt = &now
		return true
	}

	return false
}

// CheckCommitApproval prompts the user whether they want to commit and push
// automatic fixes generated by the LLM.
func CheckCommitApproval(in io.Reader, out io.Writer) bool {
	fmt.Fprintf(out, "\n--- Auto-Fix Approval ---\n")
	fmt.Fprintf(out, "LLM automatically fixed build errors. Do you want to commit and push these fixes? [y/N]: ")

	scanner := bufio.NewScanner(in)
	if !scanner.Scan() {
		return false
	}
	
	ans := strings.ToLower(strings.TrimSpace(scanner.Text()))
	if ans == "y" || ans == "yes" {
		return true
	}

	return false
}

// RecordDeployment updates the DeploymentState with a new successful deployment URL,
// cycling the current URL to previous.
func RecordDeployment(dep *DeploymentState, newURL string) {
	if dep.DeploymentURL != nil {
		dep.PreviousDeploymentURL = dep.DeploymentURL
	}
	dep.DeploymentURL = &newURL
	// Rollback is not supported yet
	dep.RollbackAvailable = false
}

// PromptDirtyDeploy asks the user how they want to handle uncommitted changes during a deployment.
// Returns:
// 1 for "Commit, push, and deploy"
// 2 for provider-specific option (Deploy dirty for Vercel, Stash and deploy remote for others)
// 3 for "Cancel"
func PromptDirtyDeploy(provider string, in io.Reader, out io.Writer) int {
	fmt.Fprintf(out, "\n--- Dirty Working Tree Detected ---\n")
	fmt.Fprintf(out, "You have uncommitted changes in your workspace.\n")
	fmt.Fprintf(out, "How would you like to proceed with the %s deployment?\n", provider)

	fmt.Fprintf(out, "  [1] Commit, push, and deploy (creates a chore commit)\n")
	if strings.ToLower(provider) == "vercel" {
		fmt.Fprintf(out, "  [2] Deploy uncommitted changes directly (Warning: dirty local files will be uploaded)\n")
	} else {
		fmt.Fprintf(out, "  [2] Stash local changes and deploy latest remote commit (restores stash after deploy)\n")
	}
	fmt.Fprintf(out, "  [3] Cancel deployment\n")

	fmt.Fprintf(out, "Select an option [1/2/3]: ")

	scanner := bufio.NewScanner(in)
	if !scanner.Scan() {
		return 3
	}

	ans := strings.TrimSpace(scanner.Text())
	switch ans {
	case "1":
		return 1
	case "2":
		return 2
	default:
		return 3
	}
}
