package orchestrator

import (
	"bufio"
	"fmt"
	"io"
	"strings"
	"time"

	"github.com/Yashh56/atlas/internal/config"
	"github.com/Yashh56/atlas/internal/cliutil"
	"github.com/charmbracelet/huh"
	"os"
)

// CheckApproval determines if a deployment is approved based on config.
// If config.Approval is "manual", it prompts the user on stdout/stdin.
// If config.Approval is "auto", it approves immediately.
// Returns true if approved, false if declined.
func CheckApproval(cfg *config.Config, dep *DeploymentState, in io.Reader, out io.Writer) bool {
	if cfg.Approval == "auto" {
		now := time.Now().UTC()
		user := "auto"
		dep.Approval.Required = false
		dep.Approval.ApprovedBy = &user
		dep.Approval.ApprovedAt = &now
		return true
	}

	// Manual approval
	fmt.Fprintf(out, "\n%s\n", cliutil.FormatHeader("Deployment Approval"))
	fmt.Fprintf(out, "%s\n", cliutil.FormatStep("Provider:   ", dep.Provider))
	fmt.Fprintf(out, "%s\n", cliutil.FormatStep("Environment:", dep.Environment))
	
	var approved bool
	if in == os.Stdin {
		approved, _ = cliutil.PromptConfirm("Proceed with deployment?")
	} else {
		fmt.Fprintf(out, "Proceed with deployment? [y/N]: ")
		scanner := bufio.NewScanner(in)
		if scanner.Scan() {
			ans := strings.ToLower(strings.TrimSpace(scanner.Text()))
			approved = (ans == "y" || ans == "yes")
		}
	}

	if approved {
		now := time.Now().UTC()
		user := "cli-user"
		dep.Approval.Required = true
		dep.Approval.ApprovedBy = &user
		dep.Approval.ApprovedAt = &now
		return true
	}

	return false
}

// CheckCommitApproval prompts the user whether they want to commit and push
// automatic fixes generated by the LLM.
func CheckCommitApproval(in io.Reader, out io.Writer) bool {
	fmt.Fprintf(out, "\n%s\n", cliutil.FormatHeader("Auto-Fix Approval"))
	fmt.Fprintf(out, "LLM automatically fixed build errors.\n")
	
	var approved bool
	if in == os.Stdin {
		approved, _ = cliutil.PromptConfirm("Do you want to commit and push these fixes?")
	} else {
		fmt.Fprintf(out, "Do you want to commit and push these fixes? [y/N]: ")
		scanner := bufio.NewScanner(in)
		if scanner.Scan() {
			ans := strings.ToLower(strings.TrimSpace(scanner.Text()))
			approved = (ans == "y" || ans == "yes")
		}
	}
	return approved
}

// RecordDeployment updates the DeploymentState with a new successful deployment URL,
// cycling the current URL to previous.
func RecordDeployment(dep *DeploymentState, newURL string) {
	if dep.DeploymentURL != nil {
		dep.PreviousDeploymentURL = dep.DeploymentURL
	}
	dep.DeploymentURL = &newURL
	// Rollback is not supported yet
	dep.RollbackAvailable = false
}

// PromptDirtyDeploy asks the user how they want to handle uncommitted changes during a deployment.
// Returns:
// 1 for "Commit, push, and deploy"
// 2 for provider-specific option (Deploy dirty for Vercel, Stash and deploy remote for others)
// 3 for "Cancel"
func PromptDirtyDeploy(provider string, in io.Reader, out io.Writer) int {
	fmt.Fprintf(out, "\n%s\n", cliutil.FormatHeader("Dirty Working Tree Detected"))
	fmt.Fprintf(out, "You have uncommitted changes in your workspace.\n")
	fmt.Fprintf(out, "How would you like to proceed with the %s deployment?\n\n", cliutil.StyleHighlight.Render(provider))

	opt1 := "Commit, push, and deploy (creates a chore commit)"
	opt2 := "Stash local changes and deploy latest remote commit (restores stash after deploy)"
	if strings.ToLower(provider) == "vercel" {
		opt2 = "Deploy uncommitted changes directly (Warning: dirty local files will be uploaded)"
	}
	opt3 := "Cancel deployment"

	var choice int
	
	// Use huh interactive select
	form := huh.NewForm(
		huh.NewGroup(
			huh.NewSelect[int]().
				Title("Select an option:").
				Options(
					huh.NewOption(opt1, 1),
					huh.NewOption(opt2, 2),
					huh.NewOption(opt3, 3),
				).
				Value(&choice),
		),
	)

	err := form.Run()
	if err != nil {
		return 3 // Cancel on error or abort
	}

	return choice
}
